# Generated by Django 6.0.6 on 2026-06-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0002_rename_broken_price_sale_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
