# Generated by Django 6.0.6 on 2026-06-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0003_production_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lot',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
