# Generated by Django 6.0.6 on 2026-06-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0004_farm_capacity_lot_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='normal_eggs',
            new_name='casiers_produits',
        ),
        migrations.RenameField(
            model_name='production',
            old_name='broken_eggs',
            new_name='oeufs_casses',
        ),
        migrations.RemoveField(
            model_name='production',
            name='deformed_eggs',
        ),
        migrations.AddField(
            model_name='farm',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='bags_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='feed_type',
            field=models.CharField(default='Standard', max_length=255),
        ),
        migrations.AddField(
            model_name='feed',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='dose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='veterinarian',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='animal_type',
            field=models.CharField(default='Pondeuses', max_length=100),
        ),
        migrations.AddField(
            model_name='lot',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='casiers_vendables',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reminder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chickenmovement',
            name='type',
            field=models.CharField(choices=[('MORT', 'Mort'), ('MALADE', 'Malade'), ('GUERI', 'Guéri'), ('AJOUT', 'Ajout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feed',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='lot',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
