# Generated by Django 6.0.6 on 2026-06-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0006_sale_remaining_amount_alter_sale_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='remaining_amount',
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_type',
            field=models.CharField(default='Oeufs', max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
