# Generated by Django 6.0.6 on 2026-06-19 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0009_rename_amount_payroll_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lots',
            field=models.ManyToManyField(blank=True, related_name='employees', to='farm_management.lot'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='farm_management.lot'),
        ),
    ]
