# Generated by Django 6.0.6 on 2026-06-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0010_employee_lots_payroll_month_task_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='repetition',
            field=models.CharField(default='ONCE', max_length=50),
        ),
        migrations.AddField(
            model_name='reminder',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
