# Generated by Django 6.0.6 on 2026-06-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0014_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('EN_PREPARATION', 'En préparation'), ('EN_PRODUCTION', 'En production'), ('TERMINE', 'Terminé'), ('VENDU', 'Vendu')], default='EN_PRODUCTION', max_length=50),
        ),
    ]
