# Generated by Django 6.0.6 on 2026-06-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0015_alter_lot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment_frequency',
            field=models.CharField(choices=[('MENSUEL', 'Mensuel'), ('SEMESTRIEL', 'Semestriel'), ('ANNUEL', 'Annuel')], default='MENSUEL', max_length=20),
        ),
    ]
