# Generated by Django 6.0.6 on 2026-06-22 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0017_feedpurchase_healthpurchase_feedinventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpurchase',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_purchases', to='farm_management.lot'),
        ),
    ]
