# Generated by Django 6.0.6 on 2026-06-22 16:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0018_feedpurchase_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='animal_type',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='task',
            name='lot',
        ),
        migrations.AddField(
            model_name='farmuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='farmuser',
            name='role',
            field=models.CharField(default='Worker', max_length=50),
        ),
        migrations.AddField(
            model_name='healthpurchase',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_purchases', to='farm_management.lot'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='PRESENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmuser',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='farm_management.farm'),
        ),
        migrations.AlterField(
            model_name='farmuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('EN_PREPARATION', 'En préparation'), ('EN_PRODUCTION', 'En production'), ('TERMINE', 'Terminé'), ('VENDU', 'Vendu')], default='EN_PREPARATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payment_method',
            field=models.CharField(default='CASH', max_length=50),
        ),
        migrations.AlterField(
            model_name='production',
            name='casiers_vendables',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_type',
            field=models.CharField(default='Œufs Normaux', max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
