# Generated by Django 6.0.6 on 2026-06-24 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0019_remove_attendance_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MORTALITE', 'Mortalité'), ('MALADIE', 'Maladie'), ('GUERISON', 'Guérison'), ('AJOUT', 'Ajout')], max_length=20)),
                ('color', models.CharField(choices=[('RED', 'Rouge'), ('ORANGE', 'Orange'), ('GREEN', 'Vert'), ('BLUE', 'Bleu')], max_length=20)),
                ('is_viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_alerts', to='farm_management.farm')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_alerts', to='farm_management.lot')),
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_alert', to='farm_management.chickenmovement')),
                ('viewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
