# Generated by Django 6.0.6 on 2026-06-25 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0020_healthalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickenmovement',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='feed',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='feedpurchase',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_purchase_origin', to='farm_management.expense'),
        ),
        migrations.AddField(
            model_name='feedpurchase',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='healthpurchase',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_purchase_origin', to='farm_management.expense'),
        ),
        migrations.AddField(
            model_name='healthpurchase',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_origin', to='farm_management.expense'),
        ),
        migrations.AddField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20),
        ),
    ]
