# Generated by Django 6.0.6 on 2026-06-26 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0021_chickenmovement_status_expense_status_feed_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedinventory',
            options={'verbose_name_plural': 'Feed Inventories (Raw Materials)'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_type',
            field=models.CharField(choices=[('NORMAL', 'Œufs Normaux'), ('BROKEN', 'Œufs Cassés')], default='NORMAL', max_length=20),
        ),
        migrations.CreateModel(
            name='FeedPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_name', models.CharField(max_length=255)),
                ('quantity_produced_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_preparations', to='farm_management.farm')),
            ],
        ),
        migrations.CreateModel(
            name='FeedPreparationIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('quantity_used_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='farm_management.feedpreparation')),
            ],
        ),
        migrations.CreateModel(
            name='PreparedFeedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_name', models.CharField(max_length=255)),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_feed_inventory', to='farm_management.farm')),
            ],
            options={
                'verbose_name_plural': 'Prepared Feed Inventories',
                'unique_together': {('farm', 'feed_name')},
            },
        ),
    ]
