# Generated by Django 6.0.6 on 2026-06-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0022_alter_feedinventory_options_alter_sale_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinventory',
            name='product_type',
            field=models.CharField(default='Autre', max_length=100),
        ),
        migrations.AddField(
            model_name='healthpurchase',
            name='product_type',
            field=models.CharField(default='Autre', max_length=100),
        ),
    ]
