# Generated by Django 6.0.6 on 2026-06-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0023_healthinventory_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinventory',
            name='consumption_unit',
            field=models.CharField(default='ml', max_length=50),
        ),
        migrations.AddField(
            model_name='healthinventory',
            name='content_per_unit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='healthinventory',
            name='purchase_unit',
            field=models.CharField(default='Flacon', max_length=50),
        ),
        migrations.AddField(
            model_name='healthpurchase',
            name='consumption_unit',
            field=models.CharField(default='ml', max_length=50),
        ),
        migrations.AddField(
            model_name='healthpurchase',
            name='content_per_unit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='healthpurchase',
            name='purchase_unit',
            field=models.CharField(default='Flacon', max_length=50),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='dose_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='dose_unit',
            field=models.CharField(default='ml', max_length=50),
        ),
    ]
