# Generated by Django 6.0.6 on 2026-06-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0024_healthinventory_consumption_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthinventory',
            old_name='purchase_unit',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='healthpurchase',
            old_name='purchase_unit',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='healthrecord',
            old_name='dose_quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='healthinventory',
            name='consumption_unit',
        ),
        migrations.RemoveField(
            model_name='healthinventory',
            name='content_per_unit',
        ),
        migrations.RemoveField(
            model_name='healthpurchase',
            name='consumption_unit',
        ),
        migrations.RemoveField(
            model_name='healthpurchase',
            name='content_per_unit',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='dose_unit',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='unit',
            field=models.CharField(default='Flacon', max_length=50),
        ),
    ]
