# Generated by Django 6.0.6 on 2026-06-26 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0025_rename_purchase_unit_healthinventory_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='farm_management.farm'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='farm_management.lot'),
        ),
    ]
