# Generated by Django 6.0.6 on 2026-06-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0026_activitylog_farm_activitylog_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
