# Generated by Django 6.0.6 on 2026-06-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0027_activitylog_related_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpreparation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20),
        ),
    ]
