# Generated by Django 6.0.6 on 2026-06-26 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0028_feedpreparation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedinventory',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_inventory', to='farm_management.lot'),
        ),
        migrations.AddField(
            model_name='feedpreparation',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_preparations', to='farm_management.lot'),
        ),
        migrations.AddField(
            model_name='healthinventory',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_inventory', to='farm_management.lot'),
        ),
        migrations.AddField(
            model_name='preparedfeedinventory',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepared_feed_inventory', to='farm_management.lot'),
        ),
    ]
