# Generated by Django 6.0.6 on 2026-06-26 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0029_feedinventory_lot_feedpreparation_lot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedinventory',
            unique_together={('lot', 'feed_type')},
        ),
        migrations.RemoveField(
            model_name='feedpreparation',
            name='farm',
        ),
        migrations.AlterUniqueTogether(
            name='healthinventory',
            unique_together={('lot', 'product_name')},
        ),
        migrations.AlterUniqueTogether(
            name='preparedfeedinventory',
            unique_together={('lot', 'feed_name')},
        ),
        migrations.AlterField(
            model_name='feedinventory',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_inventory', to='farm_management.lot'),
        ),
        migrations.AlterField(
            model_name='feedpreparation',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_preparations', to='farm_management.lot'),
        ),
        migrations.AlterField(
            model_name='healthinventory',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_inventory', to='farm_management.lot'),
        ),
        migrations.AlterField(
            model_name='preparedfeedinventory',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_feed_inventory', to='farm_management.lot'),
        ),
        migrations.RemoveField(
            model_name='feedinventory',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='healthinventory',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='preparedfeedinventory',
            name='farm',
        ),
    ]
