# Generated by Django 6.0.6 on 2026-06-26 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0030_alter_feedinventory_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus_type', models.CharField(choices=[('PERFORMANCE', 'Prime performance'), ('EXCEPTIONNEL', 'Prime exceptionnelle'), ('AUTRE', 'Autre')], default='PERFORMANCE', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='farm_management.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
