# Generated by Django 6.0.6 on 2026-06-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0031_add_bonus_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20),
        ),
    ]
