# Generated by Django 6.0.6 on 2026-06-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0032_bonus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='motif_fin',
            field=models.CharField(blank=True, choices=[('VENTE_TOTALE', 'Vente totale des poules'), ('MORTALITE_TOTALE', 'Mortalité totale'), ('FIN_ELEVAGE', "Fin d'élevage"), ('MANUEL', 'Terminaison manuelle')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chickenmovement',
            name='type',
            field=models.CharField(choices=[('MORT', 'Mort'), ('MALADE', 'Malade'), ('GUERI', 'Guéri'), ('AJOUT', 'Ajout'), ('VENTE', 'Vente')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('TERMINE', 'Terminé'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_type',
            field=models.CharField(choices=[('NORMAL', 'Œufs Normaux'), ('BROKEN', 'Œufs Cassés'), ('CHICKEN', 'Poules')], default='NORMAL', max_length=20),
        ),
    ]
