# Generated by Django 6.0.6 on 2026-06-27 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0033_lot_motif_fin_alter_chickenmovement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickenmovement',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chicken_movement', to='farm_management.sale'),
        ),
    ]
