# Generated by Django 6.0.6 on 2026-06-27 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0034_chickenmovement_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='clock_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='farm_management.farm'),
        ),
        migrations.AddField(
            model_name='task',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='farm_management.lot'),
        ),
        migrations.AlterField(
            model_name='healthalert',
            name='color',
            field=models.CharField(choices=[('RED', 'Rouge'), ('ORANGE', 'Orange'), ('GREEN', 'Vert'), ('BLUE', 'Bleu'), ('PURPLE', 'Violet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='healthalert',
            name='type',
            field=models.CharField(choices=[('MORTALITE', 'Mortalité'), ('MALADIE', 'Maladie'), ('GUERISON', 'Guérison'), ('AJOUT', 'Ajout'), ('VENTE', 'Vente')], max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CONGE', 'Congé'), ('PERMISSION', 'Permission'), ('MATERIEL', 'Matériel'), ('AUTRE', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Acceptée'), ('REJECTED', 'Refusée')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='farm_management.employee')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_requests', to='farm_management.farm')),
            ],
        ),
    ]
