# Generated by Django 6.0.6 on 2026-06-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0035_attendance_clock_in_attendance_clock_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('SANTE', 'Santé'), ('ALIMENTATION', 'Alimentation'), ('PRODUCTION', 'Production'), ('ENTRETIEN', 'Entretien'), ('GESTION_LOT', 'Gestion lot'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='type',
            field=models.CharField(choices=[('CONGE', 'Congé'), ('PERMISSION', 'Permission'), ('MATERIEL', 'Matériel'), ('PROBLEME_ELEVAGE', 'Problème élevage'), ('AUTRE', 'Autre')], max_length=20),
        ),
    ]
