# Generated by Django 6.0.6 on 2026-06-27 21:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0038_alter_attendance_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lot',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='farm_management.lot'),
        ),
    ]
