# Generated by Django 6.0.6 on 2026-06-27 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0039_alter_attendance_created_at_alter_attendance_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='farm_management.lot'),
        ),
    ]
