# Generated by Django 6.0.6 on 2026-06-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0041_expense_created_by_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='status',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=20),
        ),
    ]
