# Generated by Django 6.0.6 on 2026-08-05 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0044_add_lot_expense_and_lot_cost_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('NON_PAYE', 'Non Payé'), ('PARTIELLEMENT_PAYE', 'Partiellement Payé'), ('PAYE', 'Payé')], default='NON_PAYE', max_length=20),
        ),
        migrations.CreateModel(
            name='EggConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('from_state', models.CharField(default='EN_ATTENTE', max_length=50)),
                ('to_state', models.CharField(default='VENDABLE', max_length=50)),
                ('conversion_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_conversions', to='farm_management.farm')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_conversions', to='farm_management.lot')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='farm_management.production')),
            ],
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(default='CASH', max_length=50)),
                ('payment_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_payments_created', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_payments', to='farm_management.farm')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_payments', to='farm_management.lot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='farm_management.sale')),
            ],
        ),
    ]
