# Generated by Django 6.0.6 on 2026-08-05 02:42

from django.db import migrations


def create_sale_payments(apps, schema_editor):
    Sale = apps.get_model('farm_management', 'Sale')
    SalePayment = apps.get_model('farm_management', 'SalePayment')
    
    # Trouver toutes les ventes ayant un montant payé > 0
    sales = Sale.objects.filter(amount_paid__gt=0)
    for sale in sales:
        if not SalePayment.objects.filter(sale=sale).exists():
            SalePayment.objects.create(
                sale=sale,
                farm=sale.lot.farm,
                lot=sale.lot,
                amount=sale.amount_paid,
                payment_method='CASH',
                payment_date=sale.date,
                reference='MIGRATION',
                note='Paiement généré automatiquement depuis l\'historique.',
                status=sale.status,
                created_by=sale.created_by,
                created_at=sale.created_at,
                updated_at=sale.updated_at
            )
            
            # Mise à jour du statut
            if float(sale.amount_paid) >= float(sale.total_amount):
                sale.payment_status = 'PAYE'
            else:
                sale.payment_status = 'PARTIELLEMENT_PAYE'
            sale.save()

def reverse_create_sale_payments(apps, schema_editor):
    SalePayment = apps.get_model('farm_management', 'SalePayment')
    SalePayment.objects.filter(reference='MIGRATION').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0045_sale_payment_status_eggconversion_salepayment'),
    ]

    operations = [
        migrations.RunPython(create_sale_payments, reverse_create_sale_payments),
    ]
