# Generated by Django 6.0.6 on 2026-08-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0046_migrate_existing_sales_to_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='period_key',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
