# Generated by Django 6.0.7 on 2026-08-15 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0047_payroll_period_key_alter_payroll_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_origin', to='farm_management.expense'),
        ),
    ]
