# Generated by Django 6.0.6 on 2026-08-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0049_adminauditlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['-created_at'], name='farm_manage_created_a84c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['admin_user', '-created_at'], name='farm_manage_admin_u_5acfe9_idx'),
        ),
    ]
