# Generated by Django 6.0.6 on 2026-08-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0050_adminauditlog_farm_manage_created_a84c8e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
