# Generated by Django 6.0.6 on 2026-08-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0051_passwordresetcode_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code',
            field=models.CharField(max_length=128),
        ),
    ]
