# Generated by Django 6.0.7 on 2026-09-02 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0054_reminder_push_sent_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('resource', models.CharField(max_length=64)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['resource', 'object_id'], name='farm_manage_resourc_061d40_idx')],
            },
        ),
    ]
