# Generated by Django 6.0.6 on 2026-09-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0055_syncidempotencykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpurchase',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='healthpurchase',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
